tokens = [
'BOOL',
'LEFTARROW',
'GT',
'GE',
'LT',
'LE',
'LPARAN',
'RPARAN',
'LSQRB',
'RSQRB',
'BLOCKBEGIN',
'BLOCKEND',
'OP_NOT',
'OP_ADD',
'OP_SUB',
'OP_DIV',
'OP_MUL',
'OP_MOD',
'EQ',
'NEQ',
'AND',
'OR',
'XOR',
'AND_BIT',
'OR_BIT',
'LSHIFT',
'RSHIFT',
'RRSHIFT',
'EQUALASGN',
'ADDASGN',
'SUBASGN',
'MULASGN',
'DIVASGN',
'MODASGN',
'LSHIFTASGN',
'RSHIFTASGN',
'ANDASGN',
'ORASGN',
'XORASGN',
'COLON',
'SEMICOLON',
'DOT',
'COMMA',
'ID',
'CHAR',
'STRING',
'INT',
'FLOAT',
'SCOMMENT',
'MCOMMENT'
]

reserved = {
	'abstract' : 'R_ABSTRACT',
	'case' : 'R_CASE',
	'catch' : 'R_CATCH',
	'class' : 'R_CLASS',
	'do' : 'R_DO',
    'def': 'R_DEF',
    'dcl': 'R_DCL',
    'else' : 'R_ELSE',
	'extends' : 'R_EXTENDS',
	'final' : 'R_FINAL',
	'finally' : 'R_FINALLY',
	'for' : 'R_FOR',
	'if' : 'R_IF',
	'import' : 'R_IMPORT',
    'Int' : 'TYPE_INT',
    'String': 'TYPE_STRING',
    'Char': 'TYPE_CHAR',
    'Array':'TYPE_ARRAY',
    'Float':'TYPE_FLOAT',
    'Boolean':'TYPE_BOOLEAN',
	'new' : 'R_NEW',
	'null' : 'R_NULL',
	'object' : 'R_OBJECT',
	'override' : 'R_OVERRIDE',
	'package' : 'R_PACKAGE',
	'private' : 'R_PRIVATE',
	'protected' : 'R_PROTECTED',
    'public': 'R_PUBLIC',
    'return' : 'R_RETURN',
	'super' : 'R_SUPER',
    'switch': 'R_SWITCH',
	'this' : 'R_THIS',
	'try' : 'R_TRY',
	'val' : 'R_VAL',
	'var' : 'R_VAR',
	'while' : 'R_WHILE',
        'default' : 'R_DEFAULT'
}

tokens = tokens + list(reserved.values())
